name: Unit tests

on:
  release:
    types: [created]
  pull_request:
    branches:
      - main
      - v0.5
    paths:
      - "**.go"
      - "!e2e/**" # exclude changes in e2e tests
      - ".github/workflows/unit-tests.yaml"
      - "hack/test.sh"

jobs:
  unit-test:
    name: Execute all tests
    runs-on: ubuntu-18.04
    steps:
      - name: Set up Go 1.18
        uses: actions/setup-go@v1
        with:
          go-version: 1.18
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Execute unit tests
        run: ./hack/test.sh